### ISSUE TITLE
Existe alguma página que possamos fazer para ajudar no segundo turno?

### ISSUE THREAD

**Issue by teles** [tiantifascista/TIcomBoulos#47]
Oi, tudo bem?

Ontem mesmo estava perguntando a amigos se existiria algum tipo de página simples sem backend que possamos construir para ajudar a virar votos em SP?

Além de não ter a ideia definida fiquei com uma dúvida que não sei responder:
* Criar um site de propaganda seria legal juridicamente ? 

Quanto a ideias, todas que surgiram não empolgaram:
* Página com figurinhas pro WhatsApp
* Página em que vc entra e diz qual candidato votou no primeiro turno, qual seu campo de interesse "Segurança", "Saúde", etc.. e a partir disso recebe uma lista de motivos pra votar 50
* Algum quizz desse tipo para pessoa descobrir se tem aderência a propostas do Boulos https://squizze.github.io/squizze/#/question/1

Então é isso, se alguém tiver uma ideia em que eu consiga ajudar um pouco posso tentar ajudar. E alguém sabe se isso é legal?

Abraço

**Comment by rsip22** [comment]
Melhor forma de ajudar no momento => [Doe Boulos](https://doeboulos.com/)

Outras formas de ajudar: [https://virasp.com.br/participe/](https://virasp.com.br/participe/)

**Comment by teles** [comment]
Valeu, @rsip22 :)
